name: fitted_text_field_container
description: A Container that automatically resizes to fit a the text value of a Material TextField.
homepage: https://medium.com/@huyffs/fitted-textfield-container-for-flutter-c9c63644441c
repository: https://github.com/huyffs/fitted_text_field_container

version: 3.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true